### ISSUE TITLE
CloudFront error?

### ISSUE THREAD

**Issue by 097115** [mrusme/reader#2]
When I try `reader https://thecyberwire.com/newsletters/daily-briefing/11/27`, I get the following error:

        The request could not be satisfied
    
      --------
    
      Request blocked. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
    
      If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
    
      --------
    
        Generated by cloudfront (CloudFront)
        Request ID: i4xQcPMNFlmTno3nrQbJTLYqCSqGzgRnvJaD4CxQk6_p4OsoJwd8CA==

At the same time, I can open [the very same page](https://thecyberwire.com/newsletters/daily-briefing/11/27) in `w3m` without any problems.

**Comment by mrusme** [comment]
Interesting, will investigate. I assume it has something to do with the user-agent.

**Comment by 097115** [comment]
> I assume it has something to do with the user-agent.

Was thinking exactly this. May be adding an option that would allow us to specify a custom UA could help? 

Thanks for your support and interest!

**Comment by mrusme** [comment]
@097115 fixed the issue. The custom UA options sounds good, added #3 for that.

**Comment by 097115** [comment]
@mrusme Thanks! Can confirm, it works now :)

(And I checked the `--no-images` option, too, it's also great, so thank you once again for the support :)
