### ISSUE TITLE
Improve visibility on demonstration GIF

### ISSUE THREAD

**Issue by paxsali** [mrusme/reader#4]
Hi,

can you please fix your demonstration gif in such a way that it is accessible and easy to understand for users what the usecase of your project is?

The current gif is entirely unusable to the point where I think it's a joke, a trolling attempt.

Crop the rest of your very beautiful wallpaper and present a more visible section of the actual demo / your terminal.

Thank you for considering this change in advance.

**Comment by mrusme** [comment]
@paxsali thanks for suggesting. I changed the title of this into something that's a bit more constructive.

I had a hard time recording and cutting that gif under Linux. Happy for suggestions or maybe even support here. It's a 1920 x something size gif, if you're able to, feel free to cut and PR it in the way you think it's best.

**Comment by paxsali** [comment]
I have a suggestion to make:

- checkout [asciinema - Terminal session recorder 📹](https://github.com/asciinema/asciinema)

This is how most ppl record their terminal demonstrations.

Using tools such as [asciicast2gif - converts asciicast files to animated GIF files](https://github.com/pettarin/asciicast2gif) or services like [gifcast: Convert asciinema to animated GIF in the browser](https://dstein64.github.io/gifcast/) you can convert the ascii recording to GIF.
