### ISSUE TITLE
less displays escape character literally

### ISSUE THREAD

**Issue by themariusus** [mrusme/reader#5]
without less - https://ibb.co/KmKM0X8 - `./reader https://www.iana.org/domains/reserved`
with less - https://ibb.co/BZ2mrft - `./reader https://www.iana.org/domains/reserved | less`
v012 amd64
Is there something i'm missing?

**Comment by mrusme** [comment]
That is odd indeed. I ran `reader https://www.iana.org/domains/reserved | less` locally and it looked perfectly fine. Could you check what your `less` command is? My system is using [less](https://github.com/gwsw/less), not [more](https://www.kernel.org/pub/linux/utils/util-linux/).

**Comment by themariusus** [comment]
`less 590 (PCRE2 regular expressions)
Copyright (C) 1984-2021  Mark Nudelman`
I also tried `more`, the same.
I'm thinking maybe it's "config" specific to my setup; I'm using Arch linux in the suckless simple terminal (st).

**Comment by mrusme** [comment]
Maybe give [bat](https://github.com/sharkdp/bat) a try and see whether that works. It looks like in your setup something is not interpreting the escape characters when output is piped through `less`. What happens if you `> bla` the output and then try to `less bla` or `cat bla` it?

**Comment by themariusus** [comment]
`bat` seems to work. `less` seems to need some intervention (https://itectec.com/superuser/linux-less-prompts-for-binary-file-display-when-colors-in-output/)

**Comment by mrusme** [comment]
That's interesting. It seems like `oh-my-zsh` sets that automagically. I just checked my `env` and found this:

```
LESS=-R -M --shift 5
```

When I empty it I see the same effect that you saw. Will update the documentation about this, thanks!
