### ISSUE TITLE
Any differences between -i and -o?

### ISSUE THREAD

**Issue by for-coursera** [mrusme/reader#7]
E.g., this comparison:

    diff <(reader -o https://www.bbc.com/sport/football/60548685) <(reader -i https://www.bbc.com/sport/football/60548685)

reports no differences for me :)

With `-i`, wouldn't it be more logical  to output just the usual output simply minus images? `-o`, on the other hand, looks just fine :)

(Also, an additional line break at the end of `-o` would be nice, don't you think?)

**Comment by mrusme** [comment]
Thank you for reporting this, sorry for the delay! I've fixed this issue and a new build is getting prepared [here](https://github.com/mrusme/reader/runs/7658373025?check_suite_focus=true).
