### ISSUE TITLE
Support for stdin and local files?

### ISSUE THREAD

**Issue by 097115** [mrusme/reader#8]
Would be great to use `reader` not only for remote pages but also for local HTML files and even in pipes.

**Comment by mrusme** [comment]
Implemented both, you are now able to either pass a file as argument (`reader index.hml`) or pass `-` (dash) as argument when piping (`cat index.html | reader -`).

A new release (v0.2.0) is building [here](https://github.com/mrusme/reader/runs/7658039752?check_suite_focus=true).
